// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import { registerControllers } from "stimulus-vite-helpers"

const defaultControllers = import.meta.glob("./**/*_controller.js", {
  eager: true,
})
registerControllers(application, defaultControllers)

import ScrollProgress from "stimulus-scroll-progress"
application.register("scroll-progress", ScrollProgress)

import ScrollTo from "stimulus-scroll-to"
application.register("scroll-to", ScrollTo)
